language: ruby
rvm:
  - jruby-9.1.17.0 # ruby 2.3
  - jruby-9.2.11.1 # ruby 2.5.7
  - 2.3.0
  - 2.7.0
jobs:
  include:
    - stage: linting
      rvm: 2.7.0
      script: bundle exec rake rubocop
    - stage: benchmark
      script: bundle exec ruby benchmark/complex_example.rb
      rvm: 2.7.0
    - script: bundle exec ruby benchmark/coercion.rb
      rvm: 2.7.0
    - script: bundle exec ruby benchmark/validation_only.rb
      rvm: 2.7.0
